Action:
  allOf:
    - $ref: 'thing.yaml#/Thing'
    - properties:
        actionStatus:
          description: Indicates the current disposition of the Action.
          type: ActionStatusType
        agent:
          description: >-
            The direct performer or driver of the action (animate or inanimate).
            e.g. <em>John</em> wrote a book.
          oneOf:
            - type: Person
            - type: Organization
        endTime:
          description: >-
            The endTime of something. For a reserved event or service (e.g.
            FoodEstablishmentReservation), the time that it is expected to end.
            For actions that span a period of time, when the action was
            performed. e.g. John wrote a book from January to
            <em>December</em>.<br/><br/>


            Note that Event uses startDate/endDate instead of startTime/endTime,
            even when describing dates with times. This situation may be
            clarified in future revisions.
          format: date-time
          type: string
        error:
          description: 'For failed actions, more information on the cause of the failure.'
          type: Thing
        instrument:
          description: >-
            The object that helped the agent perform the action. e.g. John wrote
            a book with <em>a pen</em>.
          type: Thing
        location:
          description: >-
            The location of for example where the event is happening, an
            organization is located, or where an action takes place.
          oneOf:
            - type: string
            - type: PostalAddress
            - type: Place
        object:
          description: >-
            The object upon which the action is carried out, whose state is kept
            intact or changed. Also known as the semantic roles patient,
            affected or undergoer (which change their state) or theme (which
            doesn't). e.g. John read <em>a book</em>.
          type: Thing
        participant:
          description: >-
            Other co-agents that participated in the action indirectly. e.g.
            John wrote a book with <em>Steve</em>.
          oneOf:
            - type: Person
            - type: Organization
        result:
          description: The result produced in the action. e.g. John wrote <em>a book</em>.
          type: Thing
        startTime:
          description: >-
            The startTime of something. For a reserved event or service (e.g.
            FoodEstablishmentReservation), the time that it is expected to
            start. For actions that span a period of time, when the action was
            performed. e.g. John wrote a book from <em>January</em> to
            December.<br/><br/>


            Note that Event uses startDate/endDate instead of startTime/endTime,
            even when describing dates with times. This situation may be
            clarified in future revisions.
          format: date-time
          type: string
        target:
          description: Indicates a target EntryPoint for an Action.
          type: EntryPoint
      type: object
  description: >-
    An action performed by a direct agent and indirect participants upon a
    direct object. Optionally happens at a location with the help of an
    inanimate instrument. The execution of the action may produce a result.
    Specific action sub-type documentation specifies the exact expectation of
    each argument/role.<br/><br/>


    See also <a
    href="http://blog.schema.org/2014/04/announcing-schemaorg-actions.html">blog
    post</a> and <a href="http://schema.org/docs/actions.html">Actions overview
    document</a>.
