MobileApplication:
  description: >-
    A software application designed specifically to work well on a mobile device
    such as a telephone.
  allOf:
    - $ref: 'softwareapplication.yaml#/SoftwareApplication'
    - type: object
      properties:
        carrierRequirements:
          type: string
          description: >-
            Specifies specific carrier(s) requirements for the application (e.g.
            an application may only work on a specific carrier network).
