ProductModel:
  allOf:
    - $ref: 'product.yaml#/Product'
    - properties:
        isVariantOf:
          description: >-
            A pointer to a base product from which this product is a variant. It
            is safe to infer that the variant inherits all product features from
            the base model, unless defined locally. This is not transitive.
          type: ProductModel
        predecessorOf:
          description: >-
            A pointer from a previous, often discontinued variant of the product
            to its newer variant.
          type: ProductModel
        successorOf:
          description: >-
            A pointer from a newer variant of a product  to its previous, often
            discontinued predecessor.
          type: ProductModel
      type: object
  description: >-
    A datasheet or vendor specification of a product (in the sense of a
    prototypical description).
