ProductModel:
  description: >-
    A datasheet or vendor specification of a product (in the sense of a
    prototypical description).
  allOf:
    - $ref: 'product.yaml#/Product'
    - type: object
      properties:
        isVariantOf:
          $ref: 'productmodel.yaml#/ProductModel'
          description: >-
            A pointer to a base product from which this product is a variant. It
            is safe to infer that the variant inherits all product features from
            the base model, unless defined locally. This is not transitive.
        predecessorOf:
          $ref: 'productmodel.yaml#/ProductModel'
          description: >-
            A pointer from a previous, often discontinued variant of the product
            to its newer variant.
        successorOf:
          $ref: 'productmodel.yaml#/ProductModel'
          description: >-
            A pointer from a newer variant of a product  to its previous, often
            discontinued predecessor.
