Product:
  allOf:
    - $ref: 'thing.yaml#/Thing'
    - properties:
        additionalProperty:
          description: >-
            A property-value pair representing an additional characteristics of
            the entitity, e.g. a product feature or another characteristic for
            which there is no matching property in schema.org.<br/><br/>


            Note: Publishers should be aware that applications designed to use
            specific schema.org properties (e.g. http://schema.org/width,
            http://schema.org/color, http://schema.org/gtin13, ...) will
            typically expect such data to be provided using those properties,
            rather than using the generic property/value mechanism.
          type: PropertyValue
        aggregateRating:
          description: >-
            The overall rating, based on a collection of reviews or ratings, of
            the item.
          type: AggregateRating
        audience:
          description: 'An intended audience, i.e. a group for whom something was created.'
          type: Audience
        award:
          description: An award won by or for this item.
          type: string
        awards:
          description: Awards won by or for this item.
          type: string
        brand:
          description: >-
            The brand(s) associated with a product or service, or the brand(s)
            maintained by an organization or business person.
          oneOf:
            - type: Organization
            - type: Brand
        category:
          description: >-
            A category for the item. Greater signs or slashes can be used to
            informally indicate a category hierarchy.
          oneOf:
            - type: string
            - type: Thing
            - type: PhysicalActivityCategory
        color:
          description: The color of the product.
          type: string
        depth:
          description: The depth of the item.
          oneOf:
            - type: QuantitativeValue
            - type: Distance
        gtin12:
          description: >-
            The GTIN-12 code of the product, or the product to which the offer
            refers. The GTIN-12 is the 12-digit GS1 Identification Key composed
            of a U.P.C. Company Prefix, Item Reference, and Check Digit used to
            identify trade items. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
          type: string
        gtin13:
          description: >-
            The GTIN-13 code of the product, or the product to which the offer
            refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13.
            Former 12-digit UPC codes can be converted into a GTIN-13 code by
            simply adding a preceeding zero. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
          type: string
        gtin14:
          description: >-
            The GTIN-14 code of the product, or the product to which the offer
            refers. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
          type: string
        gtin8:
          description: >-
            The <a
            href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-8.aspx">GTIN-8</a>
            code of the product, or the product to which the offer refers. This
            code is also known as EAN/UCC-8 or 8-digit EAN. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
          type: string
        height:
          description: The height of the item.
          oneOf:
            - type: Distance
            - type: QuantitativeValue
        isAccessoryOrSparePartFor:
          description: >-
            A pointer to another product (or multiple products) for which this
            product is an accessory or spare part.
          type: Product
        isConsumableFor:
          description: >-
            A pointer to another product (or multiple products) for which this
            product is a consumable.
          type: Product
        isRelatedTo:
          description: >-
            A pointer to another, somehow related product (or multiple
            products).
          oneOf:
            - type: Product
            - type: Service
        isSimilarTo:
          description: >-
            A pointer to another, functionally similar product (or multiple
            products).
          oneOf:
            - type: Product
            - type: Service
        itemCondition:
          description: >-
            A predefined value from OfferItemCondition or a textual description
            of the condition of the product or service, or the products or
            services included in the offer.
          type: OfferItemCondition
        logo:
          description: An associated logo.
          oneOf:
            - type: URL
            - type: ImageObject
        manufacturer:
          description: The manufacturer of the product.
          type: Organization
        material:
          description: >-
            A material that something is made from, e.g. leather, wool, cotton,
            paper.
          oneOf:
            - type: Product
            - type: string
            - type: URL
        model:
          description: >-
            The model of the product. Use with the URL of a ProductModel or a
            textual representation of the model identifier. The URL of the
            ProductModel can be from an external source. It is recommended to
            additionally provide strong product identifiers via the
            gtin8/gtin13/gtin14 and mpn properties.
          oneOf:
            - type: ProductModel
            - type: string
        mpn:
          description: >-
            The Manufacturer Part Number (MPN) of the product, or the product to
            which the offer refers.
          type: string
        offers:
          description: >-
            An offer to provide this item&#x2014;for example, an offer to sell a
            product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
          type: Offer
        productID:
          description: >-
            The product identifier, such as ISBN. For example: <code>meta
            itemprop="productID" content="isbn:123-456-789"</code>.
          type: string
        productionDate:
          description: 'The date of production of the item, e.g. vehicle.'
          format: date
          type: string
        purchaseDate:
          description: The date the item e.g. vehicle was purchased by the current owner.
          format: date
          type: string
        releaseDate:
          description: >-
            The release date of a product or product model. This can be used to
            distinguish the exact variant of a product.
          format: date
          type: string
        review:
          description: A review of the item.
          type: Review
        reviews:
          description: Review of the item.
          type: Review
        sku:
          description: >-
            The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier
            for a product or service, or the product to which the offer refers.
          type: string
        weight:
          description: The weight of the product or person.
          type: QuantitativeValue
        width:
          description: The width of the item.
          oneOf:
            - type: QuantitativeValue
            - type: Distance
      type: object
  description: >-
    Any offered product or service. For example: a pair of shoes; a concert
    ticket; the rental of a car; a haircut; or an episode of a TV show streamed
    online.
