Product:
  description: >-
    Any offered product or service. For example: a pair of shoes; a concert
    ticket; the rental of a car; a haircut; or an episode of a TV show streamed
    online.
  allOf:
    - $ref: 'thing.yaml#/Thing'
    - type: object
      properties:
        isSimilarTo:
          oneOf:
            - $ref: 'product.yaml#/Product'
            - $ref: 'service.yaml#/Service'
          description: >-
            A pointer to another, functionally similar product (or multiple
            products).
        color:
          type: string
          description: The color of the product.
        manufacturer:
          $ref: 'organization.yaml#/Organization'
          description: The manufacturer of the product.
        gtin12:
          type: string
          description: >-
            The GTIN-12 code of the product, or the product to which the offer
            refers. The GTIN-12 is the 12-digit GS1 Identification Key composed
            of a U.P.C. Company Prefix, Item Reference, and Check Digit used to
            identify trade items. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
        isRelatedTo:
          oneOf:
            - $ref: 'service.yaml#/Service'
            - $ref: 'product.yaml#/Product'
          description: >-
            A pointer to another, somehow related product (or multiple
            products).
        gtin8:
          type: string
          description: >-
            The <a
            href="http://apps.gs1.org/GDD/glossary/Pages/GTIN-8.aspx">GTIN-8</a>
            code of the product, or the product to which the offer refers. This
            code is also known as EAN/UCC-8 or 8-digit EAN. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
        purchaseDate:
          type: string
          format: date
          description: The date the item e.g. vehicle was purchased by the current owner.
        model:
          oneOf:
            - $ref: 'productmodel.yaml#/ProductModel'
            - type: string
          description: >-
            The model of the product. Use with the URL of a ProductModel or a
            textual representation of the model identifier. The URL of the
            ProductModel can be from an external source. It is recommended to
            additionally provide strong product identifiers via the
            gtin8/gtin13/gtin14 and mpn properties.
        review:
          $ref: 'review.yaml#/Review'
          description: A review of the item.
        depth:
          oneOf:
            - $ref: 'quantitativevalue.yaml#/QuantitativeValue'
            - $ref: 'distance.yaml#/Distance'
          description: The depth of the item.
        gtin14:
          type: string
          description: >-
            The GTIN-14 code of the product, or the product to which the offer
            refers. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
        gtin13:
          type: string
          description: >-
            The GTIN-13 code of the product, or the product to which the offer
            refers. This is equivalent to 13-digit ISBN codes and EAN UCC-13.
            Former 12-digit UPC codes can be converted into a GTIN-13 code by
            simply adding a preceeding zero. See <a
            href="http://www.gs1.org/barcodes/technical/idkeys/gtin">GS1 GTIN
            Summary</a> for more details.
        itemCondition:
          $ref: 'offeritemcondition.yaml#/OfferItemCondition'
          description: >-
            A predefined value from OfferItemCondition or a textual description
            of the condition of the product or service, or the products or
            services included in the offer.
        brand:
          oneOf:
            - $ref: 'organization.yaml#/Organization'
            - $ref: 'brand.yaml#/Brand'
          description: >-
            The brand(s) associated with a product or service, or the brand(s)
            maintained by an organization or business person.
        sku:
          type: string
          description: >-
            The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier
            for a product or service, or the product to which the offer refers.
        additionalProperty:
          $ref: 'propertyvalue.yaml#/PropertyValue'
          description: >-
            A property-value pair representing an additional characteristics of
            the entitity, e.g. a product feature or another characteristic for
            which there is no matching property in schema.org.<br/><br/>


            Note: Publishers should be aware that applications designed to use
            specific schema.org properties (e.g. http://schema.org/width,
            http://schema.org/color, http://schema.org/gtin13, ...) will
            typically expect such data to be provided using those properties,
            rather than using the generic property/value mechanism.
        reviews:
          $ref: 'review.yaml#/Review'
          description: Review of the item.
        aggregateRating:
          $ref: 'aggregaterating.yaml#/AggregateRating'
          description: >-
            The overall rating, based on a collection of reviews or ratings, of
            the item.
        isAccessoryOrSparePartFor:
          $ref: 'product.yaml#/Product'
          description: >-
            A pointer to another product (or multiple products) for which this
            product is an accessory or spare part.
        isConsumableFor:
          $ref: 'product.yaml#/Product'
          description: >-
            A pointer to another product (or multiple products) for which this
            product is a consumable.
        award:
          type: string
          description: An award won by or for this item.
        mpn:
          type: string
          description: >-
            The Manufacturer Part Number (MPN) of the product, or the product to
            which the offer refers.
        width:
          oneOf:
            - $ref: 'distance.yaml#/Distance'
            - $ref: 'quantitativevalue.yaml#/QuantitativeValue'
          description: The width of the item.
        productionDate:
          type: string
          format: date
          description: 'The date of production of the item, e.g. vehicle.'
        height:
          oneOf:
            - $ref: 'distance.yaml#/Distance'
            - $ref: 'quantitativevalue.yaml#/QuantitativeValue'
          description: The height of the item.
        weight:
          $ref: 'quantitativevalue.yaml#/QuantitativeValue'
          description: The weight of the product or person.
        productID:
          type: string
          description: >-
            The product identifier, such as ISBN. For example: <code>meta
            itemprop="productID" content="isbn:123-456-789"</code>.
        material:
          oneOf:
            - type: string
            - $ref: 'product.yaml#/Product'
            - $ref: 'url.yaml#/URL'
          description: >-
            A material that something is made from, e.g. leather, wool, cotton,
            paper.
        category:
          oneOf:
            - type: object
              description: >-
                Type: PhysicalActivityCategory This type is not published yet in
                schema.org.
            - type: string
            - $ref: 'thing.yaml#/Thing'
          description: >-
            A category for the item. Greater signs or slashes can be used to
            informally indicate a category hierarchy.
        audience:
          $ref: 'audience.yaml#/Audience'
          description: 'An intended audience, i.e. a group for whom something was created.'
        releaseDate:
          type: string
          format: date
          description: >-
            The release date of a product or product model. This can be used to
            distinguish the exact variant of a product.
        awards:
          type: string
          description: Awards won by or for this item.
        logo:
          oneOf:
            - $ref: 'imageobject.yaml#/ImageObject'
            - $ref: 'url.yaml#/URL'
          description: An associated logo.
        offers:
          $ref: 'offer.yaml#/Offer'
          description: >-
            An offer to provide this item&#x2014;for example, an offer to sell a
            product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
