Service:
  allOf:
    - $ref: 'intangible.yaml#/Intangible'
    - properties:
        aggregateRating:
          description: >-
            The overall rating, based on a collection of reviews or ratings, of
            the item.
          type: AggregateRating
        areaServed:
          description: The geographic area where a service or offered item is provided.
          oneOf:
            - type: AdministrativeArea
            - type: string
            - type: Place
            - type: GeoShape
        audience:
          description: 'An intended audience, i.e. a group for whom something was created.'
          type: Audience
        availableChannel:
          description: >-
            A means of accessing the service (e.g. a phone bank, a web site, a
            location, etc.).
          type: ServiceChannel
        award:
          description: An award won by or for this item.
          type: string
        brand:
          description: >-
            The brand(s) associated with a product or service, or the brand(s)
            maintained by an organization or business person.
          oneOf:
            - type: Brand
            - type: Organization
        broker:
          description: >-
            An entity that arranges for an exchange between a buyer and a
            seller.  In most cases a broker never acquires or releases ownership
            of a product or service involved in an exchange.  If it is not clear
            whether an entity is a broker, seller, or buyer, the latter two
            terms are preferred.
          oneOf:
            - type: Organization
            - type: Person
        category:
          description: >-
            A category for the item. Greater signs or slashes can be used to
            informally indicate a category hierarchy.
          oneOf:
            - type: Thing
            - type: PhysicalActivityCategory
            - type: string
        hasOfferCatalog:
          description: >-
            Indicates an OfferCatalog listing for this Organization, Person, or
            Service.
          type: OfferCatalog
        hoursAvailable:
          description: The hours during which this service or contact is available.
          type: OpeningHoursSpecification
        isRelatedTo:
          description: >-
            A pointer to another, somehow related product (or multiple
            products).
          oneOf:
            - type: Service
            - type: Product
        isSimilarTo:
          description: >-
            A pointer to another, functionally similar product (or multiple
            products).
          oneOf:
            - type: Service
            - type: Product
        logo:
          description: An associated logo.
          oneOf:
            - type: URL
            - type: ImageObject
        offers:
          description: >-
            An offer to provide this item&#x2014;for example, an offer to sell a
            product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
          type: Offer
        produces:
          description: >-
            The tangible thing generated by the service, e.g. a passport,
            permit, etc.
          type: Thing
        provider:
          description: >-
            The service provider, service operator, or service performer; the
            goods producer. Another party (a seller) may offer those services or
            goods on behalf of the provider. A provider may also serve as the
            seller.
          oneOf:
            - type: Organization
            - type: Person
        providerMobility:
          description: >-
            Indicates the mobility of a provided service (e.g. 'static',
            'dynamic').
          type: string
        review:
          description: A review of the item.
          type: Review
        serviceArea:
          description: The geographic area where the service is provided.
          oneOf:
            - type: GeoShape
            - type: AdministrativeArea
            - type: Place
        serviceAudience:
          description: The audience eligible for this service.
          type: Audience
        serviceOutput:
          description: >-
            The tangible thing generated by the service, e.g. a passport,
            permit, etc.
          type: Thing
        serviceType:
          description: >-
            The type of service being offered, e.g. veterans' benefits,
            emergency relief, etc.
          type: string
        termsOfService:
          description: Human-readable terms of service documentation.
          oneOf:
            - type: URL
            - type: string
      type: object
  description: >-
    A service provided by an organization, e.g. delivery service, print
    services, etc.
