Service:
  allOf:
    - $ref: 'intangible.yaml#/Intangible'
    - properties:
        aggregateRating:
          $ref: 'aggregaterating.yaml#/AggregateRating'
          description: >-
            The overall rating, based on a collection of reviews or ratings, of
            the item.
        areaServed:
          description: The geographic area where a service or offered item is provided.
          oneOf:
            - $ref: 'administrativearea.yaml#/AdministrativeArea'
            - type: string
            - $ref: 'place.yaml#/Place'
            - $ref: 'geoshape.yaml#/GeoShape'
        audience:
          $ref: 'audience.yaml#/Audience'
          description: 'An intended audience, i.e. a group for whom something was created.'
        availableChannel:
          $ref: 'servicechannel.yaml#/ServiceChannel'
          description: >-
            A means of accessing the service (e.g. a phone bank, a web site, a
            location, etc.).
        award:
          description: An award won by or for this item.
          type: string
        brand:
          description: >-
            The brand(s) associated with a product or service, or the brand(s)
            maintained by an organization or business person.
          oneOf:
            - $ref: 'brand.yaml#/Brand'
            - $ref: 'organization.yaml#/Organization'
        broker:
          description: >-
            An entity that arranges for an exchange between a buyer and a
            seller.  In most cases a broker never acquires or releases ownership
            of a product or service involved in an exchange.  If it is not clear
            whether an entity is a broker, seller, or buyer, the latter two
            terms are preferred.
          oneOf:
            - $ref: 'organization.yaml#/Organization'
            - $ref: 'person.yaml#/Person'
        category:
          description: >-
            A category for the item. Greater signs or slashes can be used to
            informally indicate a category hierarchy.
          oneOf:
            - $ref: 'thing.yaml#/Thing'
            - description: >-
                PhysicalActivityCategory type is not published yet in
                schema.org.
              type: object
            - type: string
        hasOfferCatalog:
          $ref: 'offercatalog.yaml#/OfferCatalog'
          description: >-
            Indicates an OfferCatalog listing for this Organization, Person, or
            Service.
        hoursAvailable:
          $ref: 'openinghoursspecification.yaml#/OpeningHoursSpecification'
          description: The hours during which this service or contact is available.
        isRelatedTo:
          description: >-
            A pointer to another, somehow related product (or multiple
            products).
          oneOf:
            - $ref: 'service.yaml#/Service'
            - $ref: 'product.yaml#/Product'
        isSimilarTo:
          description: >-
            A pointer to another, functionally similar product (or multiple
            products).
          oneOf:
            - $ref: 'service.yaml#/Service'
            - $ref: 'product.yaml#/Product'
        logo:
          description: An associated logo.
          oneOf:
            - $ref: 'url.yaml#/URL'
            - $ref: 'imageobject.yaml#/ImageObject'
        offers:
          $ref: 'offer.yaml#/Offer'
          description: >-
            An offer to provide this item&#x2014;for example, an offer to sell a
            product, rent the DVD of a movie, perform a service, or give away
            tickets to an event.
        produces:
          $ref: 'thing.yaml#/Thing'
          description: >-
            The tangible thing generated by the service, e.g. a passport,
            permit, etc.
        provider:
          description: >-
            The service provider, service operator, or service performer; the
            goods producer. Another party (a seller) may offer those services or
            goods on behalf of the provider. A provider may also serve as the
            seller.
          oneOf:
            - $ref: 'organization.yaml#/Organization'
            - $ref: 'person.yaml#/Person'
        providerMobility:
          description: >-
            Indicates the mobility of a provided service (e.g. 'static',
            'dynamic').
          type: string
        review:
          $ref: 'review.yaml#/Review'
          description: A review of the item.
        serviceArea:
          description: The geographic area where the service is provided.
          oneOf:
            - $ref: 'geoshape.yaml#/GeoShape'
            - $ref: 'administrativearea.yaml#/AdministrativeArea'
            - $ref: 'place.yaml#/Place'
        serviceAudience:
          $ref: 'audience.yaml#/Audience'
          description: The audience eligible for this service.
        serviceOutput:
          $ref: 'thing.yaml#/Thing'
          description: >-
            The tangible thing generated by the service, e.g. a passport,
            permit, etc.
        serviceType:
          description: >-
            The type of service being offered, e.g. veterans' benefits,
            emergency relief, etc.
          type: string
        termsOfService:
          description: Human-readable terms of service documentation.
          oneOf:
            - $ref: 'url.yaml#/URL'
            - type: string
      type: object
  description: >-
    A service provided by an organization, e.g. delivery service, print
    services, etc.
