SoftwareApplication:
  allOf:
    - $ref: 'creativework.yaml#/CreativeWork'
    - properties:
        applicationCategory:
          description: 'Type of software application, e.g. ''Game, Multimedia''.'
          oneOf:
            - type: string
            - $ref: 'url.yaml#/URL'
        applicationSubCategory:
          description: 'Subcategory of the application, e.g. ''Arcade Game''.'
          oneOf:
            - type: string
            - $ref: 'url.yaml#/URL'
        applicationSuite:
          description: >-
            The name of the application suite to which the application belongs
            (e.g. Excel belongs to Office).
          type: string
        availableOnDevice:
          description: >-
            Device required to run the application. Used in cases where a
            specific make/model is required to run the application.
          type: string
        countriesNotSupported:
          description: >-
            Countries for which the application is not supported. You can also
            provide the two-letter ISO 3166-1 alpha-2 country code.
          type: string
        countriesSupported:
          description: >-
            Countries for which the application is supported. You can also
            provide the two-letter ISO 3166-1 alpha-2 country code.
          type: string
        device:
          description: >-
            Device required to run the application. Used in cases where a
            specific make/model is required to run the application.
          type: string
        downloadUrl:
          $ref: 'url.yaml#/URL'
          description: 'If the file can be downloaded, URL to download the binary.'
        featureList:
          description: >-
            Features or modules provided by this application (and possibly
            required by other applications).
          oneOf:
            - $ref: 'url.yaml#/URL'
            - type: string
        fileSize:
          description: >-
            Size of the application / package (e.g. 18MB). In the absence of a
            unit (MB, KB etc.), KB will be assumed.
          type: string
        installUrl:
          $ref: 'url.yaml#/URL'
          description: >-
            URL at which the app may be installed, if different from the URL of
            the item.
        memoryRequirements:
          description: Minimum memory requirements.
          oneOf:
            - type: string
            - $ref: 'url.yaml#/URL'
        operatingSystem:
          description: 'Operating systems supported (Windows 7, OSX 10.6, Android 1.6).'
          type: string
        permissions:
          description: >-
            Permission(s) required to run the app (for example, a mobile app may
            require full internet access or may run only on wifi).
          type: string
        processorRequirements:
          description: Processor architecture required to run the application (e.g. IA64).
          type: string
        releaseNotes:
          description: Description of what changed in this version.
          oneOf:
            - $ref: 'url.yaml#/URL'
            - type: string
        requirements:
          description: >-
            Component dependency requirements for application. This includes
            runtime environments and shared libraries that are not included in
            the application distribution package, but required to run the
            application (Examples: DirectX, Java or .NET runtime).
          oneOf:
            - $ref: 'url.yaml#/URL'
            - type: string
        screenshot:
          description: A link to a screenshot image of the app.
          oneOf:
            - $ref: 'imageobject.yaml#/ImageObject'
            - $ref: 'url.yaml#/URL'
        softwareAddOn:
          $ref: 'softwareapplication.yaml#/SoftwareApplication'
          description: Additional content for a software application.
        softwareHelp:
          $ref: 'creativework.yaml#/CreativeWork'
          description: Software application help.
        softwareRequirements:
          description: >-
            Component dependency requirements for application. This includes
            runtime environments and shared libraries that are not included in
            the application distribution package, but required to run the
            application (Examples: DirectX, Java or .NET runtime).
          oneOf:
            - $ref: 'url.yaml#/URL'
            - type: string
        softwareVersion:
          description: Version of the software instance.
          type: string
        storageRequirements:
          description: Storage requirements (free space required).
          oneOf:
            - type: string
            - $ref: 'url.yaml#/URL'
        supportingData:
          $ref: 'datafeed.yaml#/DataFeed'
          description: Supporting data for a SoftwareApplication.
      type: object
  description: A software application.
