TrainReservation:
  $ref: 'reservation.yaml#/Reservation'
  description: >-
    A reservation for train travel.<br/><br/>


    Note: This type is for information about actual reservations, e.g. in
    confirmation emails or HTML pages with individual confirmations of
    reservations. For offers of tickets, use <a class="localLink"
    href="http://schema.org/Offer">Offer</a>.
