WebApplication:
  allOf:
    - $ref: 'softwareapplication.yaml#/SoftwareApplication'
    - properties:
        browserRequirements:
          description: >-
            Specifies browser requirements in human-readable text. For example,
            'requires HTML5 support'.
          type: string
      type: object
  description: Web applications.
